### PR TITLE
Fix #36

### LINKED ISSUE #36: getRows() returns null after being called once
L: 8.9.0

Hey there,

Seems like a regression. Before, I was calling `->getRows()->first()` three times to check the header contents of three columns.

Now, the two second calls both return `null`.

Also, I was checking for duplicates using `->getRows()->uniqueStrict()` which works fine, but then, after that, I need to renew the `SimpleExcelReader` instance to be able to process the file.

I'll take a look in the commits to see what's happening.

### PR DESCRIPTION
**Pull request by ahallhognason**
Closes #36 

Fixes calling getRows() more than once, tests added.

### CODE REVIEW

**Review by Francismori7 — APPROVED** [review]
The missing flag for skips was the one causing issues, the second pass on the file would skip all rows, basically returning `[]`

File: src/SimpleExcelReader.php [hunk 1]
```diff
@@ -70,6 +72,7 @@ public function getReader(): ReaderInterface
     public function skip(int $count): SimpleExcelReader
     {
         $this->skip = $count;
```
Comment (freekmurze) [inline src/SimpleExcelReader.php:74]: Can't we make `skip` nullable. That way `null` could signify that skip shouldn't be used. This way we can lose the `useSkip` instance variable.

**Review by freekmurze — CHANGES_REQUESTED** [review]

File: src/SimpleExcelReader.php (hunk 1 above)
Comment (Francismori7) [reply src/SimpleExcelReader.php:74]: Actually, leaving it as 0 would do too, it would return false in a statement.

File: src/SimpleExcelReader.php [hunk 2]
```diff
@@ -107,7 +110,7 @@ public function getRows(): LazyCollection
         }
 
         return LazyCollection::make(function () {
-            while ($this->rowIterator->valid() && $this->skip--) {
+            while ($this->rowIterator->valid() && $this->useSkip && $this->skip--) {
```
Comment (Francismori7) [inline src/SimpleExcelReader.php:113]: `while ($this->rowIterator->valid() && $this->skip && $this->skip--) {`

File: src/SimpleExcelReader.php [hunk 3]
```diff
@@ -20,6 +20,8 @@ class SimpleExcelReader
 
     private int $skip = 0;
 
+    private bool $useSkip = false;
```
Comment (Francismori7) [inline src/SimpleExcelReader.php:23]: Remove this

**Review by Francismori7 — CHANGES_REQUESTED** [review]

File: src/SimpleExcelReader.php (hunk 1 above)
Comment (ahallhognason) [reply src/SimpleExcelReader.php]: I followed Francismori7's advice below and removed useSkip, as freek wanted

**Review by Francismori7 — APPROVED** [review]

**Comment by freekmurze** [comment]
Thanks!
